version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run: docker build --target prod -t guimochila/guimochila:$CIRCLE_BRANCH .
      - run: docker push guimochila/guimochila:$CIRCLE_BRANCH
